#!/bin/bash -e

D_VERSIONS=(
  20221121
  20200807
  20191113
  20190603
  20181017
  20180102
  20170519
  20170114
  20161023
  20160709
)

declare -A SK_VERSIONS
SK_VERSIONS=(
  [20150704]=4.5
  [20150523]=4.4
  [20150214]=4.3
  [20140308]=3.7
  [20131102]=3.6
)

ROM=/usr/share/spectrum-roms/48.rom

if (($# < 2)); then
  echo "Usage: $(basename $0) VERSION SKOOLKIT_VERSION"
  echo ""
  echo "  Attempts to build a specific version of the Spectrum ROM disassembly using a"
  echo "  specific version of SkoolKit."
  echo ""
  echo "  VERSION must be one of:"
  echo ""
  for v in ${D_VERSIONS[@]} ${!SK_VERSIONS[@]}; do
    echo "    $v"
  done | sort -r | column -c 80
  echo ""
  echo "  Environment variables:"
  echo "    SKOOLKIT_ARCHIVE - directory containing SkoolKit release tarballs"
  exit 1
fi

if [[ -z $SKOOLKIT_ARCHIVE ]]; then
    echo 'SKOOLKIT_ARCHIVE is not set; aborting'
    exit 1
fi
if [[ ! -d $SKOOLKIT_ARCHIVE ]]; then
    echo "SKOOLKIT_ARCHIVE=$SKOOLKIT_ARCHIVE: directory not found"
    exit 1
fi

D_VERSION=$1
SK_VERSION=$2

SK_VERSION_INT=$(echo $SK_VERSION | tr -d .)0
SK_VERSION_INT=${SK_VERSION_INT:0:3}

odir=rom-$D_VERSION-$SK_VERSION
rm -rf $odir
mkdir $odir
cd $odir

SK_DIR=skoolkit-$SK_VERSION
tar xf $SKOOLKIT_ARCHIVE/$SK_DIR.tar.*
SK_BUILD_DIR=${SK_DIR}-build
mv $SK_DIR $SK_BUILD_DIR

HTML_OPTS=-aH
if (($D_VERSION >= 20161023)); then
    if [[ -z $DISASSEMBLY_ARCHIVE ]]; then
        echo 'DISASSEMBLY_ARCHIVE is not set; aborting'
        exit 1
    fi
    if [[ ! -d $DISASSEMBLY_ARCHIVE ]]; then
        echo "DISASSEMBLY_ARCHIVE=$DISASSEMBLY_ARCHIVE: directory not found"
        exit 1
    fi
    D_DIR=rom-disassembly-$D_VERSION
    tar xf $DISASSEMBLY_ARCHIVE/$D_DIR.tar.xz
    cp -p $D_DIR/sources/*.{skool,ref} $SK_BUILD_DIR
    find $D_DIR -name '*.css' -exec cp -p {} $SK_BUILD_DIR \;
    find $D_DIR -name rom.py -exec cp -p {} $SK_BUILD_DIR \;
elif (($D_VERSION == 20160709)); then
    wget https://github.com/skoolkid/rom/archive/${D_VERSION}.tar.gz -O - | tar xzf -
    cp -p rom-${D_VERSION}/sources/48.rom.{ctl,ref} $SK_BUILD_DIR
else
    D_SK_VERSION=${SK_VERSIONS[$D_VERSION]}
    if [[ -z $D_SK_VERSION ]]; then
        echo "Disassembly version not recognised: $D_VERSION"
        exit 1
    fi
    D_SK_DIR=skoolkit-$D_SK_VERSION
    tar xf $SKOOLKIT_ARCHIVE/$D_SK_DIR.tar.*
    SK_SRC_DIR=$D_SK_DIR-src
    mv $D_SK_DIR $SK_SRC_DIR
    cp -p $SK_SRC_DIR/examples/48.rom.{ctl,ref} $SK_BUILD_DIR
    unset HTML_OPTS
fi

cd $SK_BUILD_DIR

if (($SK_VERSION_INT < 360)); then
  binfile=48.rom.bin
  cp -p $ROM $binfile
else
  binfile=$ROM
fi

SKOOL=rom.skool
if [[ -f 48.rom.ctl ]]; then
  SKOOL=48.rom.skool
  ./sna2skool.py -o 0 -H -c 48.rom.ctl $binfile > $SKOOL
fi

./skool2html.py -t -d .. $HTML_OPTS $SKOOL
